myStore/main/routes.py
from flask import Blueprint, render_template, jsonify, request
from myStore import mongo
from flask_login import current_user
from bson.objectid import ObjectId
import json
from bson.json_util import dumps

main = Blueprint('main', __name__)
global gender
gender = None


def ret_brands(Category=None, Type=None):
  if(Category != None and Type != None):
    brands = mongo.db.items.distinct('Brand', {'Category': Category, 'Type': Type})
  elif(Category != None):
    brands = mongo.db.items.distinct('Brand', {'Category': Category})
  else:
    brands = mongo.db.items.distinct('Brand', {'Type': type})

  return brands


def ret_categories(category):
  categories = mongo.db.items.distinct('Type', {'Category': category})
  return categories


@main.route('/items/gender', methods=['POST'])
def update_home():
  gender = request.json
  categories = ret_categories(gender)
  #items = mongo.db.items.find({'Category': gender})
  brands = ret_brands(gender)
  return render_template('categories_brands.html', brands=brands, categories=categories,gender=gender)


@main.route('/', defaults={'type': 'Shirt'})
@main.route('/<string:type>')
def home(type):
  mongo.db.items.find_one_or_404({'Type': type.title()})  # just to return 404 error if there is not a single item with that thing
  items = mongo.db.items.find({'Type': type.title()})
  global itemType
  itemType = type  # so that same type of items are getched in filter results
  brands = ret_brands(type)
  categories = ret_categories('Men')
  types = mongo.db.items.distinct('Type')
  return render_template('home.html', items=items, brands=brands, categories=categories, itemType=type.title(), types=types)


@main.route('/newhome')
def newhome():
  itemsb = mongo.db.items.find({'Type': 'Bedsheet'}).limit(12)
  itemst = mongo.db.items.find({'Type': 'Top'}).limit(12)
  itemsd = mongo.db.items.find({'Type': 'Dress'}).limit(12)
  itemss = mongo.db.items.find({'Type': 'Shirt'}).limit(12)

  return render_template('newhome.html', itemsb=itemsb, itemst=itemst, itemsd=itemsd, itemss=itemss)


@main.route('/items/filter', methods=['POST'])
def filter():
  minDiscount = 0
  maxPrice = 10000
  print('here')

 # print(request.json)
  brands = request.json['Brand']
  types = request.json['Type']

  Gender=request.json['Gender']


  print('brands: ', len(brands))
  if(request.json["Price"]):
    maxPrice = 100
    for price in request.json['Price']:
      maxPrice = max(maxPrice, price)
  if(request.json["Discount"]):
    minDiscount = 100
    for discount in request.json['Discount']:
      minDiscount = min(minDiscount, discount)
  print('maxPrice is ', maxPrice)
  if(len(Gender)==0 and len(types) == 0 and len(brands)==0 ):
     items = mongo.db.items.find(
      {'$and': [
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  if(len(Gender)==0 and len(types) == 0 and len(brands)!=0):
     items = mongo.db.items.find(
      {'$and': [
          {'$or': brands},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(len(Gender)==0 and len(types)!=0 and len(brands)==0 ):
    print('dogy')
    items = mongo.db.items.find(
      {'$and': [
          {'$or': types},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(len(Gender)==0 and len(types)!=0 and len(brands)!=0):
     items = mongo.db.items.find(
      {'$and': [
          {'$or': types},
          {'$or': brands},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(len(Gender)!=0 and len(types)!=0 and len(brands)==0 ):
     items = mongo.db.items.find(
      {'$and': [
          {'Category': gender},
          {'$or':types},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(Gender is not  None and len(types)!=0 and len(brands)!=0):
     items = mongo.db.items.find(
      {'$and': [
          {'Category': Gender},
          {'$or':types},
          {'$or':brands},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(len(Gender)!=0 and len(types) == 0 and len(brands)==0 ):
    print('entering')
    items = mongo.db.items.find(
      {'$and': [
          {'Category': Gender},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  elif(len(Gender)!=0 and len(types) == 0 and len(brands)!=0):
    print('yippy')
    print(gender)
    items = mongo.db.items.find(
      {'$and': [
          {'Category': Gender},
          {'$or':brands},
          {'Price': {'$lte': maxPrice}},
          {'Discount': {'$gte': minDiscount}}
      ]
      })

  return render_template('home_items.html', items=items)
  # return(dumps(items))


@main.route('/item/<string:item_id>')
def item(item_id):
  item = mongo.db.items.find_one_or_404({"_id": ObjectId(item_id)})
  reviews_exist = mongo.db.review.find({'item_id': ObjectId(item_id)}, {'_id': 0, 'reviews': 1}).count()
  similar_products = mongo.db.items.find({'Category': item['Category'], 'Type': item['Type']}).limit(10)
  if reviews_exist:
    reviews_dict_cursor = mongo.db.review.aggregate([{'$project':
                                                      {
                                                          'rating_avg': {'$avg': '$reviews.rating'},
                                                          'number': {'$size': '$reviews'},
                                                          'reviews': '$reviews'
                                                      }
                                                      }])
  else:
    reviews_dict_cursor = None
  return render_template('item.html', item=item, reviews_cursor=reviews_dict_cursor, title=item['Description'], similar_products=similar_products)


@main.route('/search_results', methods=['GET'])
def search():
  search_input = request.args.get("q")
  search_result_count = mongo.db.items.find({'$text': {'$search': search_input}}).count()
  if search_result_count:
    search_results = mongo.db.items.find({'$text': {'$search': search_input}})
  else:
    search_results = None
  return render_template('search.html', count=search_result_count, items=search_results)


@main.route('/seller')
def seller():
  return render_template('sellerdashboard.html')

myStore/users/routes.py
import math,string,secrets
import flask_admin as admin
from datetime import datetime, timedelta
from flask import render_template, redirect, url_for, Blueprint, flash, request, redirect, send_from_directory
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import current_user, login_required, login_user, logout_user
from myStore.users.forms import RequestResetForm, ResetPasswordForm, RegistrationForm, LoginForm, DeliveryForm, ReviewForm
from myStore.seller.forms import SellerForm
from myStore.seller.forms import ItemForm
from myStore.users.utils import send_reset_email, sendPasswordSeller
from myStore import db, bcrypt, mongo
from myStore.models import User
import json
from bson.objectid import ObjectId
import os
from functools import wraps
from bson.json_util import dumps



users = Blueprint('users', __name__)
APP_ROOT = os.path.dirname(os.path.abspath(__file__))


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        existing_user = User.objects(email=form.email.data).first()
        if existing_user is None:
            hashpass = generate_password_hash(form.password.data,method='sha256')
            role = 'customer'
            if form.seller.data:
                role= 'seller'
                approved=0
                User(form.username.data, form.email.data, hashpass,role,approved).save()
                flash('Your registeration is successfull.', 'success')
                form=SellerForm()
                if(form.validate_on_submit()):
                    return render_template('registration(part-3).html',title='Completed')
                return render_template('seller_registration.html',title='Step 2',form=form)
                    
            else:
                User(form.username.data, form.email.data, hashpass,role).save()



            flash('Your account has been created. You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='register', form=form)


def roles_required(f):
  @wraps(f)
  def decorated_function(*args, **kwargs):
    id = current_user.get_id()
    print('user id : ', id)
    user= mongo.db.user.find_one({"_id": ObjectId(id)})
    print(user)
    print(user['email'], " ", user['role'])
    if user['role'] == 'customer' or user['role']=='seller':
      flash('You are not an admin')
      return render_template('errors/403.html'), 403


    return f(*args, **kwargs)
  return decorated_function


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        check_user = User.objects(email=form.email.data).first()
        if check_user and check_password_hash(check_user['password'], form.password.data):
            login_user(check_user)
            #id = current_user.get_id()
            #user_document=mongo.db.user.find_one({'_id':ObjectId(id)},{'_id':0,'role':1})
            #if user_document['role']=='admin':
             #   return redirect('/admin_')
            flash('You have been successfully logged in', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful, Please check email and password', 'danger')
    return render_template('login.html', title='login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/admin_')
@login_required
@roles_required
def admin():
    #Admin = admin(current_app)

    print(current_user.get_id())
    print("yessssssssssssssssssssssssssssss")
    approvedSellers=mongo.db.user.find({'role':'seller','approved':True})
    unapprovedSellers=mongo.db.user.find({'role':'seller','approved':False})
    
    return render_template('admin_portal.html',title='Admin portal',approvedSellers=approvedSellers,unapprovedSellers=unapprovedSellers)


@users.route('/seller/approved/<string:seller_id>', methods=['POST'])

# @login_required
# @roles_required
def seller_approved(seller_id):
    #Admin = admin(current_app)

    print(seller_id)
    print("nnnnnnnssssssssssssssssssssssssssssss")
    # generating password to be sent to seller that contains atleast 1 lowercase, uppercase, digit, punctiation
    passwordSource= string.ascii_letters +string.digits +string.punctuation
    password= secrets.choice(string.ascii_lowercase)
    password+=secrets.choice(string.ascii_uppercase)
    password+=secrets.choice(string.digits)
    password+=secrets.choice(string.punctuation)
    print('Data')    
    for i in range(0,6):
        password+=secrets.choice(passwordSource)
    hashpass = generate_password_hash(password,method='sha256')
    sellerDocument=mongo.db.user.find_one({'_id':ObjectId(seller_id)},{'_id':0,'email':1})

    #sending password to seller 
    #sendPasswordSeller(sellerDocument['email'],password)
    print('is')
    '''
    mongo.db.user.update_one({'_id':ObjectId(seller_id)},
        {
        '$set':
            {
                'approved':True,
                'password':hashpass,

            }
        })
    '''
    print('here')
    sellers=mongo.db.user.find({'role':'seller', 'approved':False})
    sellersJson=dumps(sellers)
    return sellersJson


    






@users.route('/add_wishlist/<string:item_id>', methods=['GET', 'POST'])
@login_required
def add_to_wishlist(item_id):
    id = current_user.get_id()
    item = mongo.db.user.find({'_id': ObjectId(id), 'wishlist.item_id': ObjectId(item_id)}).count()
    if item == 0:
        itemdetail = mongo.db.items.find_one({'_id': ObjectId(item_id)})
        a = {"item_id": ObjectId(item_id)}
        mongo.db.user.update_one(
            {"_id": ObjectId(id)
             },
            {"$push":
             {"wishlist": a
              }
             }
        )
        flash('This item has been successfully added to yor wishlist', 'success')
    else:
        flash('This item is already present in your wishlist', 'success')
    return redirect(url_for('main.home'))


@users.route('/removing/<string:item_id>', methods=['GET', 'POST'])
@login_required
def remove_from_wishlist(item_id):
    id = current_user.get_id()
    mongo.db.user.update_one(
        {"_id": ObjectId(id),
         },
        {"$pull":
            {"wishlist":
                {
                    "item_id": ObjectId(item_id),
                }
             }
         }
    )
    flash('Successfully Removed', 'success')
    return redirect(url_for('users.wishlist'))

@users.route('/my_wishlist', methods=['GET', 'POST'])
@login_required
def wishlist():
    id = current_user.get_id()
    result_cursor = mongo.db.user.aggregate([{'$match': {'_id': ObjectId(id)}},
                                  {'$project':
                                   {'_id': 0, 'wishlist': 1, 'count':
                                    {'$size': '$wishlist'}
                                    }
                                   }
                                  ])
    for result in result_cursor:
        if result['count']>0:
            count=result['count']
            print(count)
            items = mongo.db.user.aggregate([
                {'$match': {'_id': ObjectId(id)}},
                {'$lookup':
                 {
                     'from': 'items',
                     'localField': 'wishlist.item_id',
                     'foreignField': '_id',
                     'as': 'item_info'
                 }
                 },
                {'$project': {'_id':0,'item_info.Category':1,'item_info._id': 1, 'item_info.Type': 1, 'item_info.Category': 1, 'item_info.Color': 1, 'item_info.Seller': 1, 'item_info.Image': 1, 'item_info.Brand': 1, 'item_info.Short Description': 1, "item_info.Price":1,"item_info.Discount":1},
                 }
            ])
            break
        else:
            count=0
            items=None
            print(count)
            break
    if(items):
        for item in items:
            items=item["item_info"]
    else:
        items=None
    return render_template('wishlist.html',items_dict=items,count=count)
@users.route('/saving/<string:item_id>', methods=['GET', 'POST'])
@login_required
def add_to_cart(item_id):
    id = current_user.get_id()
    item = mongo.db.user.find({'_id': ObjectId(id), 'item.item_id': ObjectId(item_id), 'item.size': request.form['si']}).count()
    if item==0:
        print(request.form['si'])
        itemdetail=mongo.db.items.find_one({'_id':ObjectId(item_id)})
        #this comment is to be removed on using with mlab (online databse)
        #a = {"item_id":ObjectId(item_id), "size": request.form['si'], "quantity": 1,"SellerId":itemdetail['SellerId']}
        a = {"item_id":ObjectId(item_id), "size": request.form['si'], "quantity": 1}
       
        mongo.db.user.update_one(
            {"_id": ObjectId(id)
             },
            {"$push":
             {"item": a
              }
             }
        )
        flash('This item has been successfully added to cart', 'success')
    else:
        flash('This item is already present in your cart', 'success')
    return redirect(url_for('main.home'))


@users.route('/updating/<string:item_id>/<string:item_attr>', methods=['GET', 'POST'])
@login_required
def update_cart(item_id, item_attr):
    id = current_user.get_id()
    # item=mongo.db.items.find_one({'_id': ObjectId(item_id)}, {"_id": 0, "Size": 1})
    # size=item["Size"]
    print(item_id)
    print('nefjef')
    print(item_attr)
    print(type(item_attr))
    if('qt' in request.form):
        mongo.db.user.update_one(
            {
                        "_id": ObjectId(id),
                        "item":

myStore/templates/cart.html
<br><br>
{% extends "style.html" %}
{% block content %}
<div class="container">
<ul class="inline font-weight-bold">
  <span class="left">
     <li><a href=" {{url_for('main.home')}} ">Smart Shop</a></li>
   </span>
   <span class="right">
      <i class="fa fa-lock grey" style="font-size:24px"></i> <small class="text-muted"> 100%  SECURE</small>
    </span>
   <div class="center">
    <li class="underline orange"><a href="#">Bag</a></li>
    <li>........</li>
    <li >Delivery</li>
    <li>........</li>
    <li>Payment</li>
    </div>

</ul>
<hr>
<br>
  <div class="full-box text-muted">
      <b>Offers</b>
      <ul>
        <li>Free delievery on orders above 999</li>
        <li>10% off on min spend of Rs 1499.</li>
        <li>Additional 5% off on min spend of Rs 2,999.</li>
      </ul>
  </div>
  {% if number == 0 %}
    <span class="center"><h3 class="font-weight-bold">Your shopping bag is empty. </h3></span>
  {% else %}
  <div class="seventy">
    <h3><b>My Shopping Bag ({{number}} item)</b></h3>
    {% for item in items %}
     <div class="box-1">
      <div class="cart-left">
        <img class="rounded article-image" width="150" height="150" src= " {{ url_for('static', filename=item['Category'] +'/'+item['Image'][0]) }}">
      </div>
      <b> <a href="{{ url_for('main.item',item_id=item['_id'] ) }}">{{ item["Short Description"] }} </a> </b>
      <div class="cart-right">
           <strong> Rs.{{item['quantity']*item["Price"] }} </strong>
      </div><br>
      <small class="text-muted">Sold By:<b>{{item["Seller"]}}</b></small>
      <div class="cart-right">
      {% if item["Discount"] !=0 %}
         <small class="text-muted">({{item["Discount"]}}% OFF)</small>|
        <font  color="#FF4500"><strike> Rs.{{item['quantity']*item["Mrp"] }}</strike></font>
      {% endif %}
      </div><br>
      <form name="si" action=" {{ url_for('users.update_cart', item_id=item['_id'], item_attr=item['quantity'] ) }}" method='post' >
              Size:
              <select name='si' class="btn btn-mini" onchange="this.form.submit()">
                <option>{{item["size"]}}</option>
                {% for key,value in item['Size'].items() %}
                  {% if value|int > 0 %}
                    <option value={{key}}>{{key}}</option>

                  {% else %}
                  <option value={{key}} disabled>{{key}}</option>
                  {% endif %}
                {% endfor %}
              </select>
        </form>
        <form name="si" action=" {{ url_for('users.update_cart', item_id=item['_id'], item_attr=item['size'] ) }}" method='post' >
          Qty:
            <select name='qt'class="btn btn-mini" onchange='this.form.submit()'>

        {% if item["Size"][item['size']] > 10 %}
        <option>{{item['quantity']}}</option>
          {% for q in range(1,10) %}
            Quantity:<option value={{q}} >{{q}}</option>
          {% endfor %}
        {% else %}
        <option>{{item['quantity']}}</option>
          {% for q in range(1,item["Size"][ item['size'] ] ) %}
            Quantity:<option value={{q}} >{{q}}</option>
          {% endfor %}
        {% endif %}

      </select>
      </form>
      <a class="w3-btn w3-red" href=" {{url_for('users.remove_from_cart',item_id=item['_id'], size=item['size']) }}">Remove</a></br>
    </div>
    {% endfor %} <br>
  </div>
  <div class="twenty text-muted">
    <h3 class="text-centred">Price Details</b></h3>
      <h5>Bag Total<span class="right">Rs.{{dict["bag_mrp"]}}</span></h5>
      <h5>Bag Discount <span class="right">-Rs.{{dict["bag_discount"]}}</span></h5>
      <h5>Estimated Tax<span class="right"> {{dict['tax']}}</span></h5>
      {% if dict['delivery']==0 %}
        <h5>Delivery Charges<span class="right">Free</span></h5>
      {% else %}
        <h5>Delivery Charges<span class="right">{{dict['delivery']}}</span></h5>
      {% endif %}
      {% if dict['bag_offer_discount']!=0 %}
         <h5>Offer Discount <span class="right">-Rs.{{dict["bag_offer_discount"]}}</span></h5>
      {% endif %}
      <hr>
      <h3><b>Order Total</b><span class="right"><b>Rs.{{dict['order_total']}}</b></span></h3>
       <a class="btn btn-primary btn-block"  href="{{url_for('users.checkout')}}">Place Order </a>
  </div>
</div>
  {%endif%}
{% endblock content %}

myStore/templates/home_items.html
{% for item in items %}

  <div class="box">
    <a href="{{ url_for('main.item', item_id=item['_id']) }}">
            <img class="rounded article-image" width="220" height="280" src= " {{ url_for('static', filename=item['Category']+'/'+item['Image'][0]) }}">
    </a>
    <h5><b>{{item["Brand"] }}</b></h5>
            <small class="text-muted" id="des">{{item["Short Description"]}}</small><br>
             <strong> Rs.{{item["Price"] }} </strong>
            {% if item["Discount"] !=0 %}
                <strike class="text-muted"> <small>Rs.{{item["Mrp"] }} </small></strike>  &nbsp;
              <font  color="#FF4500" >  ({{item["Discount"]}}% OFF)</font>
            {% endif %}
            <br><br>
             <a class="w3-btn w3-pink" href="{{ url_for('users.add_to_wishlist',item_id=item['_id']) }}">Add to wishlist </a>

  </div>
{% endfor %}

myStore/templates/newhome.html
{% extends "layout.html" %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100"  src= " {{ url_for('static', filename='Carousel/men1.jpg') }}" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src= " {{ url_for('static', filename='Carousel/men2.jpg') }}" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src= " {{ url_for('static', filename='Carousel/men3.jpg') }}" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src= " {{ url_for('static', filename='Carousel/women1.jpg') }}" alt="Third slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src= " {{ url_for('static', filename='Carousel/women2.jpg') }}" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<h2>BedSheets</h2>

<div class="container">
    <div class="row">
        <div class="MultiCarousel" data-items="1,3,5,6" data-slide="1" id="MultiCarousel"  data-interval="1000">
            <div class="MultiCarousel-inner">

{%for item in itemsb %}
                <a href="{{ url_for('main.item', item_id=item['_id']) }}"><div class="item" >
                    <div class="pad15" style="background-image:  url({{ url_for('static', filename=item['Category']+'/'+item['Image'][0]) }});  background-size: 150px;opacity: 0.8; ">
                        <p  class="lead">{{item["Brand"] }}</p>
                        <p >Price : ₹ {{item["Price"] }} </p>
                        <p >Mrp :<strike> ₹ {{item["Mrp"] }}</strike></p>
                        <p >{{item["Discount"]}}% OFF</p>
                    </div>
                </div></a>
  {%endfor%}

</div>
            <button class="btn btn-primary leftLst"><</button>
            <button class="btn btn-primary rightLst">></button>
        </div>
    </div>
    </div>


<h2>Dresses for Women</h2>
    <div class="container">
    <div class="row">
        <div class="MultiCarousel" data-items="1,3,5,6" data-slide="1" id="MultiCarousel"  data-interval="1000">
            <div class="MultiCarousel-inner">

{%for item in itemsd %}
                <a href="{{ url_for('main.item', item_id=item['_id']) }}"><div class="item" >
                    <div class="pad15" style="background-image:  url({{ url_for('static', filename=item['Category']+'/'+item['Image'][0]) }});  background-size: 150px;opacity: 0.8; ">
                        <p  class="lead">{{item["Brand"] }}</p>
                        <p >Price : ₹ {{item["Price"] }} </p>
                        <p >Mrp :<strike> ₹ {{item["Mrp"] }}</strike></p>
                        <p >{{item["Discount"]}}% OFF</p>
                    </div>
                </div></a>
  {%endfor%}

</div>
            <button class="btn btn-primary leftLst"><</button>
            <button class="btn btn-primary rightLst">></button>
        </div>
    </div>
    </div>
<h2>Tops</h2>
       <div class="container">
    <div class="row">
        <div class="MultiCarousel" data-items="1,3,5,6" data-slide="1" id="MultiCarousel"  data-interval="1000">
            <div class="MultiCarousel-inner">

{%for item in itemst %}
                <a href="{{ url_for('main.item', item_id=item['_id']) }}"><div class="item" >
                    <div class="pad15" style="background-image:  url({{ url_for('static', filename=item['Category']+'/'+item['Image'][0]) }});  background-size: 150px;opacity: 0.8; ">
                        <p  class="lead">{{item["Brand"] }}</p>
                        <p >Price : ₹ {{item["Price"] }} </p>
                        <p >Mrp :<strike> ₹ {{item["Mrp"] }}</strike></p>
                        <p >{{item["Discount"]}}% OFF</p>
                    </div>
                </div></a>
  {%endfor%}

</div>
            <button class="btn btn-primary leftLst"><</button>
            <button class="btn btn-primary rightLst">></button>
        </div>
    </div>
    </div>
    <h2>Shirts</h2>
       <div class="container">
    <div class="row">
        <div class="MultiCarousel" data-items="1,3,5,6" data-slide="1" id="MultiCarousel"  data-interval="1000">
            <div class="MultiCarousel-inner">

{%for item in itemss %}
                <a href="{{ url_for('main.item', item_id=item['_id']) }}"><div class="item" >
                    <div class="pad15" style="background-image:  url({{ url_for('static', filename=item['Category']+'/'+item['Image'][0]) }});  background-size: 150px;opacity: 0.8; ">
                        <p  class="lead">{{item["Brand"] }}</p>
                        <p >Price : ₹ {{item["Price"] }} </p>
                        <p >Mrp :<strike> ₹ {{item["Mrp"] }}</strike></p>
                        <p >{{item["Discount"]}}% OFF</p>
                    </div>
                </div></a>
  {%endfor%}

</div>
            <button class="btn btn-primary leftLst"><</button>
            <button class="btn btn-primary rightLst">></button>
        </div>
    </div>
    </div>


{%endblock content%}

myStore/templates/order_placed.html
<br><br><br>

{% extends "style.html" %}
{% block content %}
<div class="container">
<ul class="inline font-weight-bold">
  <span class="left">
     <li><a href=" {{url_for('main.home')}} ">Smart Shop</a></li>
   </span>
   <span class="right">
      <i class="fa fa-lock grey" style="font-size:24px"></i> <small> 100%  SECURE</small>
    </span>
   <div class="center">
    <li><a href="{{url_for('users.cart')}}">Bag</a></li>
    <li>........</li>
    <li><a href="{{url_for('users.checkout')}}">Delivery</a></li>
    <li>........</li>
    <li class="underline orange"><a href="#">Payment</a></li>
    </div>

</ul>
<hr>
 <span class="center"><h3 class="font-weight-bold">Congratulations! Your order has been placed.</h3></span>
{% endblock content %}

myStore/templates/sellerdashboard.html
{% extends "layout.html"%}
{%block content%}


<div class="container">
          <br><br><br><br>
          <h1>welcome seller</h1>
            <a class="btn btn-success btn-md" href="{{ url_for('users.login') }}"> Login </a>
            <p>Not Registered? Signup here
            </p>
            <a class="btn btn-success btn-md" href="{{ url_for('seller.additem') }}"> additem </a>
            <h2>View Items</h2>
            <a class="btn btn-success btn-md" href="{{url_for('seller.viewupdate')}}">View and Update your Items</a>
    </div>


{% endblock content %}